### ISSUE TITLE
Supported audio channels

### ISSUE THREAD

**Issue by Nama** [YuzukiHD/YuzukiLOHCC-PRO#1]
Hi,
I couldn't find anywhere how many audio channels it can record and loop to the output.

Could you please provide this information? I'm interested in recording and looping out 6 channels (5.1) from my Nintendo Switch.

**Comment by YuzukiTsuru** [comment]
MS2130 USB audio conforms to UAC1.0 protocol, and the default output is 48KHz stereo, For loop out, it is only signal transfer, which does not affect

**Comment by Nama** [comment]
Thank you!
