### ISSUE TITLE
EDA Software

### ISSUE THREAD

**Issue by phodina** [YuzukiHD/YuzukiLOHCC-PRO#11]
Hi @YuzukiTsuru ,

what EDA software do you use? How can I open the zip project file?

**Comment by 4Source** [comment]
@phodina Have you something found out on this?

**Comment by windigerbus** [comment]
They used EasyEDA Pro as far as I can tell https://pro.easyeda.com/editor

**Comment by phodina** [comment]
Thanks @Bummbumm6 . Importing the zip into Kicad (under import EsayEDA Pro project) works quite well.

CC: @4Source
