### ISSUE TITLE
jlpcb compatability

### ISSUE THREAD

**Issue by Tom-Neverwinter** [YuzukiHD/YuzukiLOHCC-PRO#2]
https://jlcpcb.com/ compatability would make this very easy for people to make and use 

[or other pcb fab stores, jlpcb has pick and place]

**Comment by YuzukiTsuru** [comment]
I made this pcb from jlcpcb, remember use the 3313

**Comment by RadegasTCZ** [comment]
It's literally in the home page. Everything else is in the master.
![image](https://user-images.githubusercontent.com/22341950/196102167-f4b61924-ae3c-4ff4-be08-280b7c173636.png)

**Comment by Tom-Neverwinter** [comment]
does it do pick and place through jlpcb?
