### ISSUE TITLE
Replace MS2130 + MS9332 by MS2131

### ISSUE THREAD

**Issue by aFooBar** [YuzukiHD/YuzukiLOHCC-PRO#3]
Replacing the [MS2130](http://www.ultrasemi.com/index.php/td-3-48-72-446) and [MS9332](http://en.macrosilicon.com/display.asp?id=119) by a single [MS2131](http://www.ultrasemi.com/index.php/td-3-48-72-450), which has an integrated HDMI loop-back, should avoid using an extra chip to split HDMI signal to get pass-through functionality. 
This should reduce BOM, cost and soldering of that already cost-effective open-source solution.

**Comment by YuzukiTsuru** [comment]
You are right, but I will not continue to launch the open source board of MS2131
