### ISSUE TITLE
SPI programmer no longer needed

### ISSUE THREAD

**Issue by BertoldVdb** [YuzukiHD/YuzukiLOHCC-PRO#4]
Hello,

I added initial MS2130 support to my MacroSilicon USB flash tool: https://github.com/BertoldVdb/ms-tools

You can flash the firmware as follows:
./cli --log-level=7 write-file --verify FLASH 0 YuzukiLOHCCPro.bin

Sincerely,
Bertold

**Comment by YuzukiTsuru** [comment]
Awsome, I added it to the readme, thanks
