### ISSUE TITLE
USB VendorID and ProductID modifications

### ISSUE THREAD

**Issue by mnm-isola** [YuzukiHD/YuzukiLOHCC-PRO#6]
Greetings, I'm currently looking if it's possible to change the VID and PID in the firmware of your open source MS2109 / MS2130 solution.

I'm in a situation where I have several embedded (and can not be tampered) Windows machine with broken cameras, and I have the idea of using MS2130 to spoof the camera check which looks for the VID and PID of the USB camera devices (and MS2130 also returns all the correct video modes already).

Wonder if it can be done by either recompiling the firmware source (if available) or by patching the firmware binary.

**Comment by YuzukiTsuru** [comment]
![image](https://github.com/YuzukiHD/YuzukiLOHCC-PRO/assets/12003087/bba73709-39bf-4dc9-a48b-81b92c411458)
 
Edit The top line of the BIN file
