### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by TechClusterHQ** [YuzukiHD/YuzukiLOHCC-PRO#7]
Hi!

Thanks for the awesome project!
I don't really understand how to properly set up and assemble the board. Is it possible to order this from JLCPCB with the chip being pre-soldered, are there gerber files for that? How would I go about soldering it myself?

Thank you.

**Comment by ilovecats4606** [comment]
[Gerber_PCB1_2022-10-06.zip](https://github.com/YuzukiHD/YuzukiLOHCC-PRO/files/12721031/Gerber_PCB1_2022-10-06.zip)

**Comment by ilovecats4606** [comment]
@TechClusterHQ

**Comment by TechClusterHQ** [comment]
@CatMow Thanks! I will still need to source and solder the chips myself, right?

**Comment by KaijaPe** [comment]
Any tips for where to find the ms8003 pre-programmed? or would the ms8005 also work?
